### ISSUE TITLE
./real.exe

### ISSUE THREAD

**Issue by cmk524411** [NCMRWF/UMRider#144]
./real.exe in WRF4.3.3 throws error while using IMDAA data that
FATAL CALLED FROM FILE:  <stdin>  LINE:    7981
 probs with sfc p computation
it seems to be Vtable and METGRID.TBL error.

can you please provide the updated or current doc path.

**Comment by arulalant** [comment]
Kindly follow this doc, and we tested IMDAA with WRF successfully. After we received your request in email, we are testing it again. Meanwhile, kindly go through this and make sure you are following all steps mentioned here properly https://rds.ncmrwf.gov.in/pdf/WRF-IMDAA_NCMRWF.pdf  & https://rds.ncmrwf.gov.in/dashboard/document. We will update here soon, after a successful test.

**Comment by arulalant** [comment]
As we communicated in email, we are able to run WRF with IMDAA, successfully. Closing this issue now.

**Comment by cmk524411** [comment]
thank you very much for all the support.

regards

**Comment by cmk524411** [comment]
thank you very much for all the support.
regards
